import { NextRequest, NextResponse } from "next/server";
import { randomUUID } from "crypto";
import { getSupabaseAdmin, getUserFromAuthHeader } from "@/lib/supabase";
import { isRateLimited, getClientIp } from "@/lib/rate-limit";

export const runtime = "nodejs";

// Vercel Functions hard-cap the REQUEST body they can receive at 4.5MB,
// platform-level — no maxDuration/config option changes it, and it applies
// before a function's own code ever runs. A phone-filmed video, even a
// short one, routinely exceeds that, which is why sending it straight in
// the POST /api/edit-video body (as FormData) kept failing with the exact
// same generic "server took too long" crash across every previous version
// of this feature, including the async start/poll rewrite — none of those
// fixes could matter, because the request was being rejected before ever
// reaching our function.
//
// The fix: the browser uploads the video directly to Supabase Storage
// (its own upload limits are separate and far higher), bypassing our
// Next.js server for the large binary entirely. This route only ever
// hands back a short-lived signed upload URL — always a tiny, fast JSON
// response, so it's never at risk of hitting that same 4.5MB ceiling
// itself.
export async function POST(req: NextRequest) {
  if (isRateLimited(`edit-video-upload-url:${getClientIp(req)}`, 20, 10 * 60 * 1000)) {
    return NextResponse.json(
      { error: "Trop de tentatives. Réessaie dans quelques minutes." },
      { status: 429 }
    );
  }

  const admin = getSupabaseAdmin();
  if (!admin) {
    return NextResponse.json(
      { error: "Connecte-toi et choisis un plan pour utiliser cette fonctionnalité." },
      { status: 401 }
    );
  }

  const authUser = await getUserFromAuthHeader(req.headers.get("authorization"));
  if (!authUser) {
    return NextResponse.json({ error: "Connexion requise." }, { status: 401 });
  }

  // Kept under a distinct "uploads/" prefix in the existing 'videos' bucket
  // (no new bucket/policy needed — createSignedUploadUrl is generated by
  // the service-role admin client and grants its own one-time authorized
  // write, independent of the bucket's normal service-role-only RLS
  // policy) so it's trivially distinguishable from — and cleaned up
  // separately from — the final transformed results stored at the bucket
  // root by app/api/edit-video/status/route.ts.
  const path = `uploads/${authUser.id}/${randomUUID()}.mp4`;

  const { data, error } = await admin.storage.from("videos").createSignedUploadUrl(path);
  if (error || !data) {
    console.error("createSignedUploadUrl error", error);
    return NextResponse.json(
      { error: "Impossible de préparer l'envoi de la vidéo. Réessaie." },
      { status: 500 }
    );
  }

  return NextResponse.json({ path: data.path, token: data.token });
}
